version: "3.0"

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - /opt/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - /opt/redis/data:/data
    networks:
      micro_net:
        aliases:
          - redis

  nginx:
    image: mdmxfry/nginx
    build: {context: ../nginx, dockerfile: Dockerfile}
    ports:
      - "80:80"
    networks:
      micro_net:

  webhook:
    build: {context: ../, dockerfile: app/Dockerfile}
    image: mdmxfry/flask_app
    networks:
      micro_net:

networks:
  micro_net: